package com.hwj.modules.collect.model;

import java.util.Date;

public class Collect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLLECT.ID
     *
     * @mbg.generated Tue Jan 16 18:40:24 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLLECT.COLLECT_TITLE
     *
     * @mbg.generated Tue Jan 16 18:40:24 CST 2018
     */
    private String collectTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLLECT.STATUS
     *
     * @mbg.generated Tue Jan 16 18:40:24 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLLECT.LAST_MODIFY_TIME
     *
     * @mbg.generated Tue Jan 16 18:40:24 CST 2018
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLLECT.COLLECT_URL
     *
     * @mbg.generated Tue Jan 16 18:40:24 CST 2018
     */
    private String collectUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLLECT.ID
     *
     * @return the value of COLLECT.ID
     *
     * @mbg.generated Tue Jan 16 18:40:24 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLLECT.ID
     *
     * @param id the value for COLLECT.ID
     *
     * @mbg.generated Tue Jan 16 18:40:24 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLLECT.COLLECT_TITLE
     *
     * @return the value of COLLECT.COLLECT_TITLE
     *
     * @mbg.generated Tue Jan 16 18:40:24 CST 2018
     */
    public String getCollectTitle() {
        return collectTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLLECT.COLLECT_TITLE
     *
     * @param collectTitle the value for COLLECT.COLLECT_TITLE
     *
     * @mbg.generated Tue Jan 16 18:40:24 CST 2018
     */
    public void setCollectTitle(String collectTitle) {
        this.collectTitle = collectTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLLECT.STATUS
     *
     * @return the value of COLLECT.STATUS
     *
     * @mbg.generated Tue Jan 16 18:40:24 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLLECT.STATUS
     *
     * @param status the value for COLLECT.STATUS
     *
     * @mbg.generated Tue Jan 16 18:40:24 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLLECT.LAST_MODIFY_TIME
     *
     * @return the value of COLLECT.LAST_MODIFY_TIME
     *
     * @mbg.generated Tue Jan 16 18:40:24 CST 2018
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLLECT.LAST_MODIFY_TIME
     *
     * @param lastModifyTime the value for COLLECT.LAST_MODIFY_TIME
     *
     * @mbg.generated Tue Jan 16 18:40:24 CST 2018
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLLECT.COLLECT_URL
     *
     * @return the value of COLLECT.COLLECT_URL
     *
     * @mbg.generated Tue Jan 16 18:40:24 CST 2018
     */
    public String getCollectUrl() {
        return collectUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLLECT.COLLECT_URL
     *
     * @param collectUrl the value for COLLECT.COLLECT_URL
     *
     * @mbg.generated Tue Jan 16 18:40:24 CST 2018
     */
    public void setCollectUrl(String collectUrl) {
        this.collectUrl = collectUrl;
    }
}